# Generated by Django 6.0.4 on 2026-04-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='user_created_at',
            new_name='user_created',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='user_updated_at',
            new_name='user_updated',
        ),
    ]
